services:
  db:
    image: postgres
    ports:
      - "5410:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eventsdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: